export * from "./AboutUs";
export { default as CarruselCards } from "./CarruselCards";
export { default as CategoriaBoton } from "./CategoriaBoton";
export { default as CategoriaBotones } from "./CategoriaBotones";
export { default as CategoriaInfo } from "./CategoriaInfo";
export { default as CategoriaTitulo } from "./CategoriaTitulo";
export { default as CategoriasCarrusel } from "./CategoriasCarrusel";
export * from "./Footer";
export * from "./Header/CartModal";
export * from "./Header/Menu";
export * from "./Header/Navbar";
export * from "./Header";
export { default as Hero } from "./Hero";
export { default as Layout } from "./Layout/Layout";
export * from "./ProductCard";
export * from "./SearchForm";
export * from "./heroPages";
export * from "./index";
