export * from "./AboutUs";
export { default as Card } from "./Card";
export { default as CarruselCards } from "./CarruselCards";
export { default as CategoriasCarrusel } from "./CategoriasCarrusel";
export * from "./Footer";
export * from "./Header/CarritoModal";
export * from "./Header/Menu";
export * from "./Header/Navbar";
export * from "./Header";
export { default as Hero } from "./Hero";
export { default as Layout } from "./Layout/Layout";
export * from "./heroPages";
export * from "./index";
